version=3.8.5
align.preset=some
align.tokens = [
  {code = "->", owner = ".*"}
  {code = "//", owner = ".*"}
]
align.stripMargin = false
assumeStandardLibraryStripMargin = true
docstrings.forceBlankLineBefore = false
docstrings.oneline = fold
docstrings.style = Asterisk
docstrings.removeEmpty = true
maxColumn = 160
newlines.topLevelStatementBlankLines = [
  {
  blanks { after = 1 }
  regex = "package*"
  }

  {
  blanks { after = 1 }
  regex = "^import"
  }
]
rewrite.rules = [AvoidInfix, Imports, RedundantBraces, RedundantParens, SortModifiers]
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.ifElseExpressions = true
rewrite.neverInfix.excludeFilters."+" = [
  "compose",
  "andThen",
  "as",
  # Lenses
  "modify",
  "set",
  # Scalatest
  "include.*",
  "length",
  "message",
  "must.*",
  "regex.*",
  "should.*",
  "theSameElementsInOrderAs",
  be,
  a,
  have,
  plus
  ]
rewrite.imports.sort = scalastyle
rewrite.imports.expand = false
rewrite.imports.groups = [
  ["cats..*", "mouse..*", "monocle..*"],
  ["java..*","scala..*"],
  ["org.scalatest..*"],
]
importSelectors = "singleline"
runner.dialect=scala3
rewrite.trailingCommas.style = always
rewrite.sortModifiers.order = [
  "private", "protected",
  "implicit",
  "final", "sealed", "abstract", "override",
  "lazy",
]
