app-config {
  name = "thalesServer"
  server-connection-config {
    host = "0.0.0.0"
    port = 443
    keystore-file = ${?KEYSTORE_FILE}
    keystore-password = ${?KEYSTORE_PASSWORD}
  }
  backend-server-config {
    number-of-workers = 4
    bounded-queue-capacity = 32
  }
  auth-config {
    secret-key = ${?JWT_SECRET_KEY}
    expiration-period-in-seconds = 28800
    allowed-renewal-period-in-seconds = 79200
    jwt-encoding-algorithm = "HS256"
  }
}
