app-config {
  db-connection-config {
    host = ${?DB_SERVER_HOST}
    port = ${?DB_SERVER_PORT}
    user = ${?DB_USERNAME}
    password = ${?DB_USERNAME_PASSWORD}
    database-name = ${?DB_NAME}
    max-connections = 32
    min-idle-connections = 16
  }
  backend-server-config {
    number-of-workers = 32
    bounded-queue-capacity = 512
  }
  mem-cache-config {
    director-mem-cache-config {
      capacity = 400
    }
    actor-mem-cache-config {
      capacity = 400
    }
    movie-mem-cache-config {
      capacity = 400
    }
  }
}
