app-config {
  name = "thalesServer"
  server-connection-config {
    host = "0.0.0.0"
    port = 443
    keystore-file = ${?KEYSTORE_FILE}
    keystore-password = ${?KEYSTORE_PASSWORD}
  }
  backend-server-config {
    number-of-workers = 4
    bounded-queue-capacity = 32
    endpoint-delays = {}
  }
  auth-config {
    secret-key = ${?JWT_SECRET_KEY}
    expiration-period-in-seconds = 7200        // Two hours
    allowed-renewal-period-in-seconds = 39600  // Eleven hours
    jwt-encoding-algorithm = "HS256"
    auth-mem-cache-capacity = 100
    auth-mem-cache-cleanup-duration-in-seconds =  600
    auth-mem-cache-cleanup-time-tick-duration-in-seconds = 5
  }
  email-outbox-worker-config {
    polling-interval = 10s
    base-backoff = 30s
  }
}
