app-config {
  db-connection-config {
      host = "localhost\\SQLEXPRESS"
      port = 63634
      user = ${?DB_USERNAME}
      password = ${?DB_USERNAME_PASSWORD}
      database-name = ${?DB_NAME}
      max-connections = 6
      min-idle-connections = 4
    }
}
