app-config {
  db-connection-config {
    host = ${?DB_SERVER_HOST}
    port = ${?DB_SERVER_PORT}
    user = ${?DB_USERNAME}
    password = ${?DB_USERNAME_PASSWORD}
    database-name = ${?DB_NAME}
    max-connections = 10
    min-idle-connections = 4
  }
}
